run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - exportloopref

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gofmt:
    simplify: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G104  # Audit errors not checked (too noisy for this project)
      - G304  # File path provided as taint input (intentional for file reading)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
    - path: pkg/parser/
      linters:
        - unparam  # Parser functions often have unused params for consistency
    - path: pkg/interpreter/
      linters:
        - unparam
  max-issues-per-linter: 50
  max-same-issues: 10
